### ISSUE TITLE
Random crash when run: "habitus -version" on mac 10.12

### ISSUE THREAD

**Issue by qiuyuzhou** [cloud66/habitus#32]
```
 qiuyuzhou  ⋯  git.shundaojia.com  servers  carpoolsch  habitus -version
Habitus - v0.4.6 (c) 2016 Cloud 66 Inc.
 qiuyuzhou  ⋯  git.shundaojia.com  servers  carpoolsch  habitus -version
Habitus - v0.4.6 (c) 2016 Cloud 66 Inc.
 qiuyuzhou  ⋯  git.shundaojia.com  servers  carpoolsch  habitus -version
Habitus - v0.4.6 (c) 2016 Cloud 66 Inc.
 qiuyuzhou  ⋯  git.shundaojia.com  servers  carpoolsch  habitus -version
failed MSpanList_Insert 0x92d000 0xb0892f31fb6 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x5e1d10, 0x10)
	/Users/khash/go/src/runtime/panic.go:530 +0x90 fp=0x7fff5fbff0c0 sp=0x7fff5fbff0a8
runtime.(*mSpanList).insert(0x82d288, 0x92d000)
	/Users/khash/go/src/runtime/mheap.go:933 +0x293 fp=0x7fff5fbff0f0 sp=0x7fff5fbff0c0
runtime.(*mheap).freeSpanLocked(0x82ca80, 0x92d000, 0x100, 0x0)
	/Users/khash/go/src/runtime/mheap.go:809 +0x4be fp=0x7fff5fbff158 sp=0x7fff5fbff0f0
runtime.(*mheap).grow(0x82ca80, 0x8, 0x0)
	/Users/khash/go/src/runtime/mheap.go:675 +0x2a0 fp=0x7fff5fbff1b0 sp=0x7fff5fbff158
runtime.(*mheap).allocSpanLocked(0x82ca80, 0x1, 0x0)
	/Users/khash/go/src/runtime/mheap.go:553 +0x4e3 fp=0x7fff5fbff208 sp=0x7fff5fbff1b0
runtime.(*mheap).alloc_m(0x82ca80, 0x1, 0x15, 0x0)
	/Users/khash/go/src/runtime/mheap.go:437 +0x119 fp=0x7fff5fbff238 sp=0x7fff5fbff208
runtime.(*mheap).alloc.func1()
	/Users/khash/go/src/runtime/mheap.go:502 +0x41 fp=0x7fff5fbff268 sp=0x7fff5fbff238
runtime.systemstack(0x7fff5fbff288)
	/Users/khash/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7fff5fbff270 sp=0x7fff5fbff268
runtime.(*mheap).alloc(0x82ca80, 0x1, 0x10000000015, 0x12a6f)
	/Users/khash/go/src/runtime/mheap.go:503 +0x63 fp=0x7fff5fbff2b8 sp=0x7fff5fbff270
runtime.(*mcentral).grow(0x82e680, 0x0)
	/Users/khash/go/src/runtime/mcentral.go:209 +0x93 fp=0x7fff5fbff320 sp=0x7fff5fbff2b8
runtime.(*mcentral).cacheSpan(0x82e680, 0x826fa8)
	/Users/khash/go/src/runtime/mcentral.go:89 +0x47d fp=0x7fff5fbff360 sp=0x7fff5fbff320
runtime.(*mcache).refill(0x929000, 0x15, 0x7fff5fbff3c8)
	/Users/khash/go/src/runtime/mcache.go:119 +0xcc fp=0x7fff5fbff398 sp=0x7fff5fbff360
runtime.mallocgc.func2()
	/Users/khash/go/src/runtime/malloc.go:642 +0x2b fp=0x7fff5fbff3b8 sp=0x7fff5fbff398
runtime.systemstack(0x7fff5fbff458)
	/Users/khash/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7fff5fbff3c0 sp=0x7fff5fbff3b8
runtime.mallocgc(0x180, 0x57bba0, 0x0, 0x800000000)
	/Users/khash/go/src/runtime/malloc.go:643 +0x869 fp=0x7fff5fbff498 sp=0x7fff5fbff3c0
runtime.newobject(0x57bba0, 0x827790)
	/Users/khash/go/src/runtime/malloc.go:781 +0x42 fp=0x7fff5fbff4c0 sp=0x7fff5fbff498
runtime.malg(0x8000, 0x827b40)
	/Users/khash/go/src/runtime/proc.go:2634 +0x27 fp=0x7fff5fbff4f8 sp=0x7fff5fbff4c0
runtime.mpreinit(0x828300)
	/Users/khash/go/src/runtime/os1_darwin.go:140 +0x1f fp=0x7fff5fbff510 sp=0x7fff5fbff4f8
runtime.mcommoninit(0x828300)
	/Users/khash/go/src/runtime/proc.go:494 +0x105 fp=0x7fff5fbff558 sp=0x7fff5fbff510
runtime.schedinit()
	/Users/khash/go/src/runtime/proc.go:434 +0x79 fp=0x7fff5fbff5a0 sp=0x7fff5fbff558
runtime.rt0_go(0x7fff5fbff5d8, 0x2, 0x7fff5fbff5d8, 0x0, 0x0, 0x2, 0x7fff5fbff7a8, 0x7fff5fbff7b0, 0x0, 0x7fff5fbff7b9, ...)
	/Users/khash/go/src/runtime/asm_amd64.s:138 +0x132 fp=0x7fff5fbff5a8 sp=0x7fff5fbff5a0
```

**Comment by qiuyuzhou** [comment]
Also random crash when building

```
2016/10/12 12:34:47 ▶ Building the builder image from Dockerfile.builder.generated 
failed MSpanList_Insert 0x9bfa78 0xe09af5b8622 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x5e1d10, 0x10)
	/Users/khash/go/src/runtime/panic.go:530 +0x90
runtime.(*mSpanList).insert(0x82d288, 0x9bfa78)
	/Users/khash/go/src/runtime/mheap.go:933 +0x293
runtime.(*mheap).freeSpanLocked(0x82ca80, 0x9bfa78, 0x100, 0x0)
	/Users/khash/go/src/runtime/mheap.go:809 +0x4be
runtime.(*mheap).grow(0x82ca80, 0x8, 0x0)
	/Users/khash/go/src/runtime/mheap.go:675 +0x2a0
runtime.(*mheap).allocSpanLocked(0x82ca80, 0x1, 0x9bfa00)
	/Users/khash/go/src/runtime/mheap.go:553 +0x4e3
runtime.(*mheap).alloc_m(0x82ca80, 0x1, 0xe, 0x9bfa00)
	/Users/khash/go/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
	/Users/khash/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x70000172bd40)
	/Users/khash/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x82ca80, 0x1, 0x1000000000e, 0x12a6f)
	/Users/khash/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x82e370, 0x0)
	/Users/khash/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x82e370, 0x28316)
	/Users/khash/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x929960, 0xe, 0xc8201bdba0)
	/Users/khash/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/Users/khash/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc82001ca00)
	/Users/khash/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/Users/khash/go/src/runtime/proc.go:1048

goroutine 7 [running]:
runtime.systemstack_switch()
	/Users/khash/go/src/runtime/asm_amd64.s:245 fp=0xc8200e0290 sp=0xc8200e0288
runtime.mallocgc(0xd0, 0x520f40, 0x0, 0xc8200e04f8)
	/Users/khash/go/src/runtime/malloc.go:643 +0x869 fp=0xc8200e0368 sp=0xc8200e0290
runtime.newobject(0x520f40, 0xc8200e04f8)
	/Users/khash/go/src/runtime/malloc.go:781 +0x42 fp=0xc8200e0390 sp=0xc8200e0368
os.Lstat(0xc8201feea0, 0x82, 0x0, 0x0, 0x0, 0x0)
	/Users/khash/go/src/os/file_unix.go:182 +0x42 fp=0xc8200e03e8 sp=0xc8200e0390
path/filepath.walk(0xc8201f5880, 0x71, 0x97d848, 0xc8201f75f0, 0xc8200e0c10, 0x0, 0x0)
	/Users/khash/go/src/path/filepath/path.go:368 +0x3a3 fp=0xc8200e0520 sp=0xc8200e03e8
path/filepath.walk(0xc8201ee000, 0x6b, 0x97d848, 0xc8201e3ba0, 0xc8200e0c10, 0x0, 0x0)
	/Users/khash/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8200e0658 sp=0xc8200e0520
path/filepath.walk(0xc8201b9e30, 0x66, 0x97d848, 0xc8201e3ad0, 0xc8200e0c10, 0x0, 0x0)
	/Users/khash/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8200e0790 sp=0xc8200e0658
path/filepath.walk(0xc8201d2360, 0x5c, 0x97d848, 0xc8201ce5b0, 0xc8200e0c10, 0x0, 0x0)
	/Users/khash/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8200e08c8 sp=0xc8200e0790
path/filepath.walk(0xc8201d21e0, 0x51, 0x97d848, 0xc8201ce4e0, 0xc8200e0c10, 0x0, 0x0)
	/Users/khash/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8200e0a00 sp=0xc8200e08c8
path/filepath.walk(0xc82013e140, 0x4a, 0x97d848, 0xc820120340, 0xc8200e0c10, 0x0, 0x0)
	/Users/khash/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8200e0b38 sp=0xc8200e0a00
path/filepath.Walk(0xc82013e140, 0x4a, 0xc8200e0c10, 0x0, 0x0)
	/Users/khash/go/src/path/filepath/path.go:396 +0xe1 fp=0xc8200e0ba0 sp=0xc8200e0b38
github.com/cloud66/habitus/vendor/github.com/fsouza/go-dockerclient.validateContextDirectory(0xc8200140f4, 0x4a, 0xc82011a460, 0x1, 0x1, 0x0, 0x0)
	/Users/khash/work/go/src/github.com/cloud66/habitus/vendor/github.com/fsouza/go-dockerclient/tar.go:105 +0x12b fp=0xc8200e0c48 sp=0xc8200e0ba0
github.com/cloud66/habitus/vendor/github.com/fsouza/go-dockerclient.createTarStream(0xc8200140f4, 0x4a, 0xc82010785b, 0x1c, 0x0, 0x0, 0x0, 0x0)
	/Users/khash/work/go/src/github.com/cloud66/habitus/vendor/github.com/fsouza/go-dockerclient/tar.go:52 +0x293 fp=0xc8200e0dd8 sp=0xc8200e0c48
github.com/cloud66/habitus/vendor/github.com/fsouza/go-dockerclient.(*Client).BuildImage(0xc8200985c8, 0xc8200f2518, 0x7, 0xc82010785b, 0x1c, 0x1000000, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/khash/work/go/src/github.com/cloud66/habitus/vendor/github.com/fsouza/go-dockerclient/image.go:486 +0x394 fp=0xc8200e1148 sp=0xc8200e0dd8
github.com/cloud66/habitus/build.(*Builder).BuildStep(0xc8200985a0, 0xc8200e1ec0, 0x0, 0x0)
	/Users/khash/work/go/src/github.com/cloud66/habitus/build/builder.go:199 +0x7d5 fp=0xc8200e1e38 sp=0xc8200e1148
github.com/cloud66/habitus/build.(*Builder).StartBuild.func1(0xc8200985a0, 0xc8200f2518, 0x7, 0xc8200f2500, 0x7, 0xc8200db9e0, 0x12, 0xc8200984b0, 0x1, 0x1, ...)
	/Users/khash/work/go/src/github.com/cloud66/habitus/build/builder.go:117 +0x159 fp=0xc8200e1eb8 sp=0xc8200e1e38
runtime.goexit()
	/Users/khash/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200e1ec0 sp=0xc8200e1eb8
created by github.com/cloud66/habitus/build.(*Builder).StartBuild
	/Users/khash/work/go/src/github.com/cloud66/habitus/build/builder.go:121 +0x54f

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc820098684)
	/Users/khash/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc820098678)
	/Users/khash/go/src/sync/waitgroup.go:127 +0xb4
github.com/cloud66/habitus/build.(*Builder).StartBuild(0xc8200985a0, 0x0, 0x0)
	/Users/khash/work/go/src/github.com/cloud66/habitus/build/builder.go:124 +0x59e
main.main()
	/Users/khash/work/go/src/github.com/cloud66/habitus/main.go:136 +0x15eb

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/khash/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/Users/khash/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/Users/khash/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/Users/khash/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [IO wait]:
net.runtime_pollWait(0x9ba000, 0x72, 0x979050)
	/Users/khash/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82011e140, 0x72, 0x0, 0x0)
	/Users/khash/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82011e140, 0x0, 0x0)
	/Users/khash/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82011e0e0, 0x0, 0x9ba0f8, 0xc8201220e0)
	/Users/khash/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc82013c000, 0xf8031, 0x0, 0x0)
	/Users/khash/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc82013c000, 0x0, 0x0, 0x0, 0x0)
	/Users/khash/go/src/net/http/server.go:2427 +0x41
net/http.(*Server).Serve(0xc82011c080, 0x9ba0c0, 0xc82013c000, 0x0, 0x0)
	/Users/khash/go/src/net/http/server.go:2117 +0x129
net/http.(*Server).ListenAndServe(0xc82011c080, 0x0, 0x0)
	/Users/khash/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0xc82011a090, 0xe, 0x9b9000, 0xc82011a0b0, 0x0, 0x0)
	/Users/khash/go/src/net/http/server.go:2195 +0x98
main.(*server).StartServer.func1(0xc82002e0e8, 0xc8200f45a0)
	/Users/khash/work/go/src/github.com/cloud66/habitus/server.go:38 +0x311
created by main.(*server).StartServer
	/Users/khash/work/go/src/github.com/cloud66/habitus/server.go:43 +0x3e3
```

**Comment by qiuyuzhou** [comment]
I built habitus by myself with go 1.7, then it's ok.

**Comment by kamerblauwlicht** [comment]
hi @qiuyuzhou. i updated the internal libraries and compiled a new version using Go 1.7. You can download v0.4.7 here: https://github.com/cloud66/habitus/releases/tag/v0.4.7
