### ISSUE TITLE
Problem with artifacts

### ISSUE THREAD

**Issue by PawelMag** [cloud66/habitus#63]
Hello,

I'm using Habitus with this yml file

```
build:  
    version: 2016-03-14
    steps:
        builder:
            name: builder
            dockerfile: Dockerfile.builder
             - /home/MainUser/test.tar.gz
        deploy:
            name: deploying
            dockerfile: Dockerfile.deploy
```

When I run it, I get following error:
```
2017/04/20 15:08:05 notifying bugsnag: regexp: Compile(`^C:\Users\Pawel\Documents\Docker\dockerKinetis/+`): error parsing regexp: invalid escape sequence: `\U`
2017/04/20 15:08:05 ? Collecting artifact information
panic: regexp: Compile(`^C:\Users\Pawel\Documents\Docker\dockerKinetis/+`): error parsing regexp: invalid escape sequence: `\U` [recovered]
        panic: regexp: Compile(`^C:\Users\Pawel\Documents\Docker\dockerKinetis/+`): error parsing regexp: invalid escape sequence: `\U`

goroutine 1 [running]:
panic(0x7dcae0, 0xc0420f7720)
        /usr/local/go/src/runtime/panic.go:500 +0x1af
github.com/cloud66/habitus/vendor/github.com/bugsnag/bugsnag-go.AutoNotify(0xc0420f7740, 0x1, 0x1)
        /usr/local/go/src/github.com/cloud66/habitus/vendor/github.com/bugsnag/bugsnag-go/bugsnag.go:52 +0x13a
panic(0x7dcae0, 0xc0420f7720)
        /usr/local/go/src/runtime/panic.go:458 +0x251
regexp.MustCompile(0xc0420f3440, 0x30, 0xc042093030)
        /usr/local/go/src/regexp/regexp.go:237 +0x181
github.com/cloud66/habitus/build.(*Builder).collectHostArtifactRoots(0xc042072780, 0xc0420f76b0, 0x1, 0x1)
        /usr/local/go/src/github.com/cloud66/habitus/build/builder.go:184 +0x30d
github.com/cloud66/habitus/build.(*Builder).StartBuild(0xc042072780, 0xc042086d80, 0xc042072780)
        /usr/local/go/src/github.com/cloud66/habitus/build/builder.go:109 +0xd49
main.main()
        /usr/local/go/src/github.com/cloud66/habitus/main.go:149 +0xe66
2017/04/20 15:08:05 notifying bugsnag: regexp: Compile(`^C:\Users\Pawel\Documents\Docker\dockerKinetis/+`): error parsing regexp: invalid escape sequence: `\U`
[recovered]
```
I don't know what I am doing wrong. Without artifacts everything is OK.

**Comment by kamerblauwlicht** [comment]
@PawelMag which version are you using? 
maybe change you build.yml to:

```
build:  
    version: 2016-03-14
    steps:
        builder:
            name: builder
            dockerfile: Dockerfile.builder
            artifacts:
             - /home/MainUser/test.tar.gz
        deploy:
            name: deploying
            dockerfile: Dockerfile.deploy
```

**Comment by PawelMag** [comment]
I'm sorry. I had to missed artifact word. But error is still the same. I'm using habitus in version 0.4.14 on windows 7. I have try with older versions too, but result is the same.

**Comment by kamerblauwlicht** [comment]
Hi @PawelMag,
There is no 0.4.14 version :-) Can you try the pre-release: **0.4.11_pre** 
https://github.com/cloud66/habitus/releases/tag/0.4.11_pre

Let me know

**Comment by PawelMag** [comment]
I'm sorry again :) I'm using v0.4.10.
I found solution for my problem.
Path to my working directory contain special sign '\U' ("C:\Users\....."). So I simply changed my working directory to "C:\temp", and everything works great. 

Thanks for your help.

**Comment by kamerblauwlicht** [comment]
hi @PawelMag good to hear you found the solution!
